# Generated by Django 2.2.6 on 2019-12-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'катогория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'номенклатура',
                'verbose_name_plural': 'справочник номенлатуры',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'ед.изм',
                'verbose_name_plural': 'единица измерения',
            },
        ),
        migrations.CreateModel(
            name='PersonalThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_things', to='personal_items.Category', verbose_name='категория')),
                ('nomenclature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_things', to='personal_items.Nomenclature', verbose_name='наименование')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_things', to='personal_items.Unit', verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'вещь',
                'verbose_name_plural': 'Личные вещи',
            },
        ),
    ]
