# Generated by Django 2.2.6 on 2019-10-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_shots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/%Y/%m/%d/', verbose_name='Готовое изображение'),
        ),
        migrations.AlterField(
            model_name='shotpart',
            name='image',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/', verbose_name='изображение'),
        ),
    ]
