# Generated by Django 2.2.6 on 2019-10-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_shots', '0002_auto_20191007_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotpart',
            name='image',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/%H_%M', verbose_name='изображение'),
        ),
    ]
