# Generated by Django 2.2.6 on 2019-10-28 20:22
import os

from django.db import migrations


def create_geo_squares_by_shots(apps, schema_editor):
    ShotPart = apps.get_model('map_shots', 'ShotPart')

    for part in ShotPart.objects.all():
        if os.path.isfile(part.image.path):
            os.remove(part.image.path)


class Migration(migrations.Migration):
    dependencies = [
        ('map_shots', '0004_auto_20191014_2119'),
    ]

    operations = [
        migrations.RunPython(
            create_geo_squares_by_shots,
            reverse_code=migrations.RunPython.noop
        ),
    ]
